#!/bin/bash
echo "Mode-N (Boost mode) [0]"
echo " Denver cores: 2, max 2.0 GHz"
echo " ARM-A57 cores: 4, max 2.0 GHz"
echo " GPU: max 1.3 GHz"
echo ""
echo "Max-Q mode [1]"
echo " Denver cores: 0"
echo " ARM-A57 cores: 4, max 1.2 GHz"
echo " GPU: max 0.85 GHz"
echo ""
echo "Max-P core-all [2]"
echo " Denver cores: 2, max 1.4 GHz"
echo " ARM-A57 cores: 4, max 1.4 GHz"
echo " GPU: max 1.12 GHz"
echo ""
echo "Max-P ARM [3]"
echo " Denver cores: 0"
echo " ARM-A57 cores: 4, max 2.0 GHz"
echo " GPU: max 1.12 GHz"
echo ""
echo "Max-P Denver [4]"
echo " Denver cores: 1, max 2.0 GHz"
echo " ARM-A57 cores: 1, max 2.0 GHz"
echo " GPU: max 1.12 GHz"
